/// Custom orbit computation using precomputed sudoku symmetry group generators.
///
/// Replaces nauty calls at intermediate search nodes with direct
/// permutation-based orbit computation. The sudoku symmetry group
/// (3,359,232 elements) is generated by 17 natural generators:
///   - row swaps within each band (6)
///   - column swaps within each stack (6)
///   - band swaps (2)
///   - stack swaps (2)
///   - transpose (1)
///
/// At startup, we expand these into a larger pool (~hundreds of elements)
/// using Schreier's lemma for Stab(cell 0) plus pairwise products.
/// At each search node, we filter the pool for set-stabilizers and
/// compute orbits via union-find. This is much faster than calling
/// nauty, though the orbits may be slightly coarser (fewer merges).

use std::collections::HashSet;
use std::sync::LazyLock;

/// A permutation of 81 cells.
type Perm = [u8; 81];

const IDENTITY: Perm = {
    let mut p = [0u8; 81];
    let mut i = 0;
    while i < 81 {
        p[i] = i as u8;
        i += 1;
    }
    p
};

// ── generator construction (all const fn) ───────────────────────────

const fn swap_rows(a: usize, b: usize) -> Perm {
    let mut p = IDENTITY;
    let mut c = 0;
    while c < 9 {
        let ra = 9 * a + c;
        let rb = 9 * b + c;
        let tmp = p[ra];
        p[ra] = p[rb];
        p[rb] = tmp;
        c += 1;
    }
    p
}

const fn swap_cols(a: usize, b: usize) -> Perm {
    let mut p = IDENTITY;
    let mut r = 0;
    while r < 9 {
        let ca = 9 * r + a;
        let cb = 9 * r + b;
        let tmp = p[ca];
        p[ca] = p[cb];
        p[cb] = tmp;
        r += 1;
    }
    p
}

const fn swap_bands(a: usize, b: usize) -> Perm {
    let mut p = IDENTITY;
    let mut k = 0;
    while k < 3 {
        let mut c = 0;
        while c < 9 {
            let ra = 9 * (3 * a + k) + c;
            let rb = 9 * (3 * b + k) + c;
            let tmp = p[ra];
            p[ra] = p[rb];
            p[rb] = tmp;
            c += 1;
        }
        k += 1;
    }
    p
}

const fn swap_stacks(a: usize, b: usize) -> Perm {
    let mut p = IDENTITY;
    let mut k = 0;
    while k < 3 {
        let mut r = 0;
        while r < 9 {
            let ca = 9 * r + (3 * a + k);
            let cb = 9 * r + (3 * b + k);
            let tmp = p[ca];
            p[ca] = p[cb];
            p[cb] = tmp;
            r += 1;
        }
        k += 1;
    }
    p
}

const fn make_transpose() -> Perm {
    let mut p = [0u8; 81];
    let mut r = 0;
    while r < 9 {
        let mut c = 0;
        while c < 9 {
            p[9 * r + c] = (9 * c + r) as u8;
            c += 1;
        }
        r += 1;
    }
    p
}

/// The 17 generators of the full sudoku symmetry group.
static BASE_GENS: [Perm; 17] = [
    swap_rows(0, 1), swap_rows(1, 2),
    swap_rows(3, 4), swap_rows(4, 5),
    swap_rows(6, 7), swap_rows(7, 8),
    swap_cols(0, 1), swap_cols(1, 2),
    swap_cols(3, 4), swap_cols(4, 5),
    swap_cols(6, 7), swap_cols(7, 8),
    swap_bands(0, 1), swap_bands(1, 2),
    swap_stacks(0, 1), swap_stacks(1, 2),
    make_transpose(),
];

// ── permutation arithmetic ──────────────────────────────────────────

/// compose(a, b)[i] = a[b[i]]: apply b first, then a.
fn compose(a: &Perm, b: &Perm) -> Perm {
    let mut p = [0u8; 81];
    for i in 0..81 {
        p[i] = a[b[i] as usize];
    }
    p
}

/// Inverse permutation.
fn invert(a: &Perm) -> Perm {
    let mut p = [0u8; 81];
    for i in 0..81 {
        p[a[i] as usize] = i as u8;
    }
    p
}

// ── Schreier generators for Stab(point) ─────────────────────────────

/// Compute generators of Stab(point) via Schreier's lemma.
///
/// Given generators of a group G acting on {0..80}, compute the orbit
/// of `point` under G (by BFS) and return generators of the subgroup
/// that fixes `point`.
fn schreier_generators(gens: &[Perm], point: u8) -> Vec<Perm> {
    // BFS: compute orbit and transversal (tv[v] maps point → v)
    let mut tv: [Option<Perm>; 81] = [None; 81];
    tv[point as usize] = Some(IDENTITY);
    let mut orbit = vec![point];
    let mut front = 0;
    while front < orbit.len() {
        let u = orbit[front];
        front += 1;
        let t_u: Perm = tv[u as usize].unwrap();
        for g in gens {
            let v = g[u as usize];
            if tv[v as usize].is_none() {
                tv[v as usize] = Some(compose(g, &t_u));
                orbit.push(v);
            }
        }
    }

    // Schreier generators: for each u in orbit and generator g,
    // s = tv[g(u)]^{-1} ∘ g ∘ tv[u] fixes `point`.
    let mut result: HashSet<Perm> = HashSet::new();
    for &u in &orbit {
        let t_u: Perm = tv[u as usize].unwrap();
        for g in gens {
            let gu = g[u as usize];
            let t_gu: Perm = tv[gu as usize].unwrap();
            let sg = compose(&invert(&t_gu), &compose(g, &t_u));
            if sg != IDENTITY {
                result.insert(sg);
            }
        }
    }
    result.into_iter().collect()
}

// ── pool construction ───────────────────────────────────────────────

const MAX_POOL_SIZE: usize = 500;

/// Precomputed pool of group elements for orbit computation.
static PERM_POOL: LazyLock<Vec<Perm>> = LazyLock::new(build_perm_pool);

fn build_perm_pool() -> Vec<Perm> {
    let mut pool: HashSet<Perm> = HashSet::new();

    // Add base generators
    for g in &BASE_GENS {
        pool.insert(*g);
    }

    // Schreier generators of Stab(cell 0) — the search always roots at cell 0
    let stab0 = schreier_generators(&BASE_GENS, 0);
    for g in &stab0 {
        pool.insert(*g);
        pool.insert(invert(g));
    }

    // Expand: products of current pool elements with base generators
    if pool.len() < MAX_POOL_SIZE {
        let current: Vec<Perm> = pool.iter().copied().collect();
        'outer: for a in &current {
            for b in &BASE_GENS {
                let ab = compose(a, b);
                if ab != IDENTITY { pool.insert(ab); }
                let ba = compose(b, a);
                if ba != IDENTITY { pool.insert(ba); }
                if pool.len() >= MAX_POOL_SIZE { break 'outer; }
            }
        }
    }

    pool.remove(&IDENTITY);

    eprintln!("symmetry: pool has {} group elements for orbit pruning", pool.len());

    pool.into_iter().collect()
}

/// Return the pool size (also forces initialization).
pub fn pool_size() -> usize {
    PERM_POOL.len()
}

// ── orbit computation ───────────────────────────────────────────────

/// Test if permutation g maps the chosen set to itself (setwise stabilizer).
/// Uses early exit: bails as soon as any chosen cell maps outside the set.
#[inline]
fn stabilizes_mask(g: &Perm, mask: u128) -> bool {
    let mut m = mask;
    while m != 0 {
        let bit = m.trailing_zeros() as usize;
        m &= m - 1;
        if mask & (1u128 << g[bit]) == 0 {
            return false;
        }
    }
    true
}

/// Compute orbit representatives for candidate cells under the setwise
/// stabilizer of the chosen pattern, using precomputed group elements.
///
/// Returns one representative per orbit of candidates (the first candidate
/// encountered in each orbit). This is always valid (never merges
/// inequivalent candidates) but may return more representatives than
/// nauty would — i.e., orbits may be finer than the true orbits.
pub fn orbit_reps_custom(chosen_mask: u128, candidates: &[u8]) -> Vec<u8> {
    if candidates.len() <= 1 {
        return candidates.to_vec();
    }

    let pool = &*PERM_POOL;

    // Build candidate mask for fast membership check
    let cand_mask: u128 = candidates.iter().fold(0u128, |m, &c| m | (1u128 << c));

    // Union-find on candidate cells
    let mut parent = [0u8; 81];
    for &c in candidates {
        parent[c as usize] = c;
    }

    // Filter pool for set-stabilizers; union candidates under their action
    for g in pool.iter() {
        if !stabilizes_mask(g, chosen_mask) {
            continue;
        }
        for &c in candidates {
            let gc = g[c as usize];
            if cand_mask & (1u128 << gc) != 0 {
                // Union c and gc
                let mut rc = c;
                while parent[rc as usize] != rc { rc = parent[rc as usize]; }
                let mut rgc = gc;
                while parent[rgc as usize] != rgc { rgc = parent[rgc as usize]; }
                if rc != rgc {
                    if rc < rgc {
                        parent[rgc as usize] = rc;
                    } else {
                        parent[rc as usize] = rgc;
                    }
                }
            }
        }
    }

    // Collect orbit representatives with path compression
    let mut seen = [false; 81];
    let mut reps = Vec::new();
    for &c in candidates {
        let mut root = c;
        while parent[root as usize] != root { root = parent[root as usize]; }
        // Path compression
        let mut x = c;
        while parent[x as usize] != root {
            let next = parent[x as usize];
            parent[x as usize] = root;
            x = next;
        }
        if !seen[root as usize] {
            seen[root as usize] = true;
            reps.push(c);
        }
    }

    reps
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generators_are_valid_perms() {
        for g in &BASE_GENS {
            let mut seen = [false; 81];
            for &v in g.iter() {
                assert!((v as usize) < 81);
                assert!(!seen[v as usize], "duplicate in permutation");
                seen[v as usize] = true;
            }
        }
    }

    #[test]
    fn generators_are_involutions() {
        for (i, g) in BASE_GENS.iter().enumerate() {
            let g2 = compose(g, g);
            assert_eq!(g2, IDENTITY, "generator {} is not an involution", i);
        }
    }

    #[test]
    fn generators_preserve_adjacency() {
        use crate::sudoku_graph::NEIGHBORS_MASK;
        for (gi, g) in BASE_GENS.iter().enumerate() {
            for u in 0..81u8 {
                for v in (u + 1)..81u8 {
                    let uv_adj = (NEIGHBORS_MASK[u as usize] >> v) & 1 != 0;
                    let gu = g[u as usize];
                    let gv = g[v as usize];
                    let guv_adj = (NEIGHBORS_MASK[gu as usize] >> gv) & 1 != 0;
                    assert_eq!(
                        uv_adj, guv_adj,
                        "generator {} doesn't preserve adjacency: u={}, v={}",
                        gi, u, v
                    );
                }
            }
        }
    }

    #[test]
    fn pool_size_reasonable() {
        let size = pool_size();
        assert!(size >= 17, "pool should have at least 17 elements, got {}", size);
        assert!(size <= 1000, "pool too large: {}", size);
        eprintln!("perm pool size: {}", size);
    }

    #[test]
    fn orbit_reps_with_single_cell_chosen() {
        use crate::sudoku_graph::NEIGHBORS_MASK;
        use crate::bitset::iter_bits;

        // With cell 0 chosen, candidates are its 20 neighbors
        let chosen = 1u128 << 0;
        let candidates: Vec<u8> = iter_bits(NEIGHBORS_MASK[0]).collect();
        assert_eq!(candidates.len(), 20);

        let reps = orbit_reps_custom(chosen, &candidates);
        // There should be significant symmetry reduction
        assert!(
            reps.len() < candidates.len(),
            "expected symmetry reduction: {} reps from {} candidates",
            reps.len(),
            candidates.len()
        );
        eprintln!(
            "cell-0 orbit reps: {} from {} candidates",
            reps.len(),
            candidates.len()
        );
    }

    #[test]
    fn transpose_merges_cell_1_and_9() {
        // Cell 1=(0,1) and cell 9=(1,0) are related by transpose.
        // Transpose fixes cell 0=(0,0). So with chosen={0}, cells 1 and 9
        // should be in the same orbit.
        let chosen = 1u128 << 0;
        let candidates = vec![1u8, 9];
        let reps = orbit_reps_custom(chosen, &candidates);
        assert_eq!(
            reps.len(),
            1,
            "cells 1 and 9 should be equivalent under transpose"
        );
    }

    #[test]
    fn custom_orbits_refine_nauty() {
        use crate::bitset::iter_bits;
        use crate::canonical::candidate_orbit_reps;
        use crate::sudoku_graph::NEIGHBORS_MASK;

        // For chosen = {0, 1, 9}, compare custom vs nauty orbit counts
        let chosen_mask = (1u128 << 0) | (1u128 << 1) | (1u128 << 9);
        let frontier = NEIGHBORS_MASK[0] | NEIGHBORS_MASK[1] | NEIGHBORS_MASK[9];
        let candidates: Vec<u8> = iter_bits(frontier & !chosen_mask).collect();

        let custom_reps = orbit_reps_custom(chosen_mask, &candidates);
        let (nauty_reps, _) = candidate_orbit_reps(chosen_mask, &candidates);

        // Custom orbits should be a refinement: at least as many reps as nauty
        assert!(
            custom_reps.len() >= nauty_reps.len(),
            "custom orbits should refine nauty: custom={}, nauty={}",
            custom_reps.len(),
            nauty_reps.len()
        );
        eprintln!(
            "orbit comparison: custom={} vs nauty={} (from {} candidates)",
            custom_reps.len(),
            nauty_reps.len(),
            candidates.len()
        );
    }
}
